environment: catbox

service:
  type: NodePort

ingress:
  ip: 34.75.53.226

randocats:
  image:
    repository: us.gcr.io/randocats/randocats
    tag: latest
    pullPolicy: Always
  replicas: 2
  name: randocats
  port: 8080